# Generated by Django 4.1.7 on 2023-04-26 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 17, 30, 24, 398975, tzinfo=datetime.timezone.utc)),
        ),
    ]
