# Generated by Django 4.2 on 2023-04-29 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_client_trial_end_date_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='working_days',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 19, 56, 44, 261363, tzinfo=datetime.timezone.utc)),
        ),
    ]
