# Generated by Django 4.2 on 2023-04-29 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_client_working_days_alter_client_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 20, 14, 11, 917132, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='client',
            name='working_days',
        ),
        migrations.AddField(
            model_name='client',
            name='working_days',
            field=models.ManyToManyField(blank=True, limit_choices_to={'date__week_day': 7}, related_name='working_days', to='book.appointment'),
        ),
    ]
