# Generated by Django 4.2 on 2023-04-29 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_client_trial_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 23, 36, 57, 524461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='client',
            name='working_days',
        ),
        migrations.AddField(
            model_name='client',
            name='working_days',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
