# Generated by Django 4.2 on 2023-05-02 01:08

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_newslettersubscriber_alter_client_trial_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 1, 8, 29, 380771, tzinfo=datetime.timezone.utc)),
        ),
    ]
