# Generated by Django 4.2 on 2023-05-02 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_newslettercontent_newslettersubscriber_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='content',
        ),
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 1, 37, 0, 680830, tzinfo=datetime.timezone.utc)),
        ),
    ]
