# Generated by Django 4.2 on 2023-05-03 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_appointment_deposit_paid_alter_client_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='describe_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 17, 17, 11, 500110, tzinfo=datetime.timezone.utc)),
        ),
    ]
