# Generated by Django 4.2 on 2023-05-05 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_category_alter_client_trial_end_date_client_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trial_end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 3, 43, 49, 89699, tzinfo=datetime.timezone.utc)),
        ),
    ]
